[2023-06-24T10:37:13.416+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag_v2.spark_submit_task manual__2023-06-24T10:37:12.446856+00:00 [queued]>
[2023-06-24T10:37:13.426+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag_v2.spark_submit_task manual__2023-06-24T10:37:12.446856+00:00 [queued]>
[2023-06-24T10:37:13.426+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-24T10:37:13.426+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-06-24T10:37:13.426+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-24T10:37:13.441+0000] {taskinstance.py:1303} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-06-24 10:37:12.446856+00:00
[2023-06-24T10:37:13.447+0000] {standard_task_runner.py:55} INFO - Started process 644 to run task
[2023-06-24T10:37:13.449+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag_v2', 'spark_submit_task', 'manual__2023-06-24T10:37:12.446856+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag2.py', '--cfg-path', '/tmp/tmpg2bhekj9']
[2023-06-24T10:37:13.450+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask spark_submit_task
[2023-06-24T10:37:13.460+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-06-24T10:37:13.508+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_airflow_dag_v2.spark_submit_task manual__2023-06-24T10:37:12.446856+00:00 [running]> on host 846f24a1d814
[2023-06-24T10:37:13.578+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_***_dag_v2
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-24T10:37:12.446856+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-24T10:37:12.446856+00:00
[2023-06-24T10:37:13.588+0000] {base.py:73} INFO - Using connection ID 'spark_connn' for task execution.
[2023-06-24T10:37:13.589+0000] {spark_submit.py:341} INFO - Spark-Submit cmd: spark-submit --master spark://172.19.0.8:7077 --name arrow-spark /opt/***/dags/spark_etl_simple.py
[2023-06-24T10:37:14.795+0000] {spark_submit.py:492} INFO - WARNING: An illegal reflective access operation has occurred
[2023-06-24T10:37:14.795+0000] {spark_submit.py:492} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2023-06-24T10:37:14.795+0000] {spark_submit.py:492} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2023-06-24T10:37:14.796+0000] {spark_submit.py:492} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2023-06-24T10:37:14.796+0000] {spark_submit.py:492} INFO - WARNING: All illegal access operations will be denied in a future release
[2023-06-24T10:37:16.003+0000] {spark_submit.py:492} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2023-06-24T10:37:16.011+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkContext: Running Spark version 3.2.0
[2023-06-24T10:37:16.086+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-06-24T10:37:16.187+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO ResourceUtils: ==============================================================
[2023-06-24T10:37:16.187+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO ResourceUtils: No custom resources configured for spark.driver.
[2023-06-24T10:37:16.187+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO ResourceUtils: ==============================================================
[2023-06-24T10:37:16.188+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkContext: Submitted application: test
[2023-06-24T10:37:16.210+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2023-06-24T10:37:16.225+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO ResourceProfile: Limiting resource is cpu
[2023-06-24T10:37:16.225+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2023-06-24T10:37:16.289+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SecurityManager: Changing view acls to: default
[2023-06-24T10:37:16.290+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SecurityManager: Changing modify acls to: default
[2023-06-24T10:37:16.290+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SecurityManager: Changing view acls groups to:
[2023-06-24T10:37:16.291+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SecurityManager: Changing modify acls groups to:
[2023-06-24T10:37:16.291+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(default); groups with view permissions: Set(); users  with modify permissions: Set(default); groups with modify permissions: Set()
[2023-06-24T10:37:16.574+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO Utils: Successfully started service 'sparkDriver' on port 41709.
[2023-06-24T10:37:16.600+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkEnv: Registering MapOutputTracker
[2023-06-24T10:37:16.630+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkEnv: Registering BlockManagerMaster
[2023-06-24T10:37:16.649+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2023-06-24T10:37:16.651+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2023-06-24T10:37:16.659+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2023-06-24T10:37:16.680+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-38740987-2b60-4a70-88d7-2a44ca980014
[2023-06-24T10:37:16.697+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2023-06-24T10:37:16.711+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2023-06-24T10:37:16.888+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2023-06-24T10:37:16.894+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2023-06-24T10:37:16.941+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:16 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://846f24a1d814:4041
[2023-06-24T10:37:17.182+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:17 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.19.0.8:7077...
[2023-06-24T10:37:17.256+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:17 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 172.19.0.8:7077
[2023-06-24T10:37:17.256+0000] {spark_submit.py:492} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2023-06-24T10:37:17.256+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2023-06-24T10:37:17.256+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2023-06-24T10:37:17.256+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:37:17.257+0000] {spark_submit.py:492} INFO - Caused by: java.io.IOException: Failed to connect to /172.19.0.8:7077
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - ... 4 more
[2023-06-24T10:37:17.258+0000] {spark_submit.py:492} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.19.0.8:7077
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - Caused by: java.net.ConnectException: Connection refused
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[2023-06-24T10:37:17.259+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[2023-06-24T10:37:17.260+0000] {spark_submit.py:492} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2023-06-24T10:37:17.260+0000] {spark_submit.py:492} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2023-06-24T10:37:17.260+0000] {spark_submit.py:492} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2023-06-24T10:37:17.260+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:37:37.182+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:37 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.19.0.8:7077...
[2023-06-24T10:37:37.187+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:37 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 172.19.0.8:7077
[2023-06-24T10:37:37.187+0000] {spark_submit.py:492} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-06-24T10:37:37.188+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - Caused by: java.io.IOException: Failed to connect to /172.19.0.8:7077
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - ... 4 more
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.19.0.8:7077
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - Caused by: java.net.ConnectException: Connection refused
[2023-06-24T10:37:37.189+0000] {spark_submit.py:492} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2023-06-24T10:37:37.190+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:37:57.184+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:57 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.19.0.8:7077...
[2023-06-24T10:37:57.205+0000] {spark_submit.py:492} INFO - 23/06/24 10:37:57 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 172.19.0.8:7077
[2023-06-24T10:37:57.206+0000] {spark_submit.py:492} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2023-06-24T10:37:57.207+0000] {spark_submit.py:492} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2023-06-24T10:37:57.207+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2023-06-24T10:37:57.207+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2023-06-24T10:37:57.208+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2023-06-24T10:37:57.208+0000] {spark_submit.py:492} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2023-06-24T10:37:57.208+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2023-06-24T10:37:57.208+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-06-24T10:37:57.209+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-06-24T10:37:57.209+0000] {spark_submit.py:492} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-06-24T10:37:57.209+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:37:57.210+0000] {spark_submit.py:492} INFO - Caused by: java.io.IOException: Failed to connect to /172.19.0.8:7077
[2023-06-24T10:37:57.210+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2023-06-24T10:37:57.210+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2023-06-24T10:37:57.211+0000] {spark_submit.py:492} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2023-06-24T10:37:57.211+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2023-06-24T10:37:57.212+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2023-06-24T10:37:57.212+0000] {spark_submit.py:492} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2023-06-24T10:37:57.213+0000] {spark_submit.py:492} INFO - ... 4 more
[2023-06-24T10:37:57.213+0000] {spark_submit.py:492} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.19.0.8:7077
[2023-06-24T10:37:57.213+0000] {spark_submit.py:492} INFO - Caused by: java.net.ConnectException: Connection refused
[2023-06-24T10:37:57.214+0000] {spark_submit.py:492} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2023-06-24T10:37:57.214+0000] {spark_submit.py:492} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2023-06-24T10:37:57.214+0000] {spark_submit.py:492} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
[2023-06-24T10:37:57.215+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2023-06-24T10:37:57.215+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
[2023-06-24T10:37:57.215+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[2023-06-24T10:37:57.216+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[2023-06-24T10:37:57.217+0000] {spark_submit.py:492} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[2023-06-24T10:37:57.217+0000] {spark_submit.py:492} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2023-06-24T10:37:57.218+0000] {spark_submit.py:492} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2023-06-24T10:37:57.218+0000] {spark_submit.py:492} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2023-06-24T10:37:57.219+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:38:17.184+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2023-06-24T10:38:17.184+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2023-06-24T10:38:17.192+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34093.
[2023-06-24T10:38:17.193+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO NettyBlockTransferService: Server created on 846f24a1d814:34093
[2023-06-24T10:38:17.194+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO SparkUI: Stopped Spark web UI at http://846f24a1d814:4041
[2023-06-24T10:38:17.195+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2023-06-24T10:38:17.201+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO StandaloneSchedulerBackend: Shutting down all executors
[2023-06-24T10:38:17.202+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 846f24a1d814, 34093, None)
[2023-06-24T10:38:17.204+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2023-06-24T10:38:17.205+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManagerMasterEndpoint: Registering block manager 846f24a1d814:34093 with 434.4 MiB RAM, BlockManagerId(driver, 846f24a1d814, 34093, None)
[2023-06-24T10:38:17.206+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 846f24a1d814, 34093, None)
[2023-06-24T10:38:17.207+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 846f24a1d814, 34093, None)
[2023-06-24T10:38:17.208+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2023-06-24T10:38:17.218+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2023-06-24T10:38:17.228+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO MemoryStore: MemoryStore cleared
[2023-06-24T10:38:17.228+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManager: BlockManager stopped
[2023-06-24T10:38:17.235+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO BlockManagerMaster: BlockManagerMaster stopped
[2023-06-24T10:38:17.237+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2023-06-24T10:38:17.248+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO SparkContext: Successfully stopped SparkContext
[2023-06-24T10:38:17.349+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 ERROR SparkContext: Error initializing SparkContext.
[2023-06-24T10:38:17.349+0000] {spark_submit.py:492} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2023-06-24T10:38:17.349+0000] {spark_submit.py:492} INFO - at scala.Predef$.require(Predef.scala:281)
[2023-06-24T10:38:17.349+0000] {spark_submit.py:492} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2023-06-24T10:38:17.349+0000] {spark_submit.py:492} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-06-24T10:38:17.350+0000] {spark_submit.py:492} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO SparkContext: SparkContext already stopped.
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - Traceback (most recent call last):
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - File "/opt/***/dags/spark_etl_simple.py", line 3, in <module>
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - spark = SparkSession.builder.appName('test').getOrCreate()
[2023-06-24T10:38:17.351+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 146, in __init__
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1573, in __call__
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - File "/opt/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 326, in get_return_value
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2023-06-24T10:38:17.352+0000] {spark_submit.py:492} INFO - at scala.Predef$.require(Predef.scala:281)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2023-06-24T10:38:17.353+0000] {spark_submit.py:492} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2023-06-24T10:38:17.354+0000] {spark_submit.py:492} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2023-06-24T10:38:17.354+0000] {spark_submit.py:492} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2023-06-24T10:38:17.354+0000] {spark_submit.py:492} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2023-06-24T10:38:17.354+0000] {spark_submit.py:492} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-24T10:38:17.354+0000] {spark_submit.py:492} INFO - 
[2023-06-24T10:38:17.392+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO ShutdownHookManager: Shutdown hook called
[2023-06-24T10:38:17.393+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-30fc2d18-68ac-409a-92b7-976ab144cc3c
[2023-06-24T10:38:17.396+0000] {spark_submit.py:492} INFO - 23/06/24 10:38:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-e05708fb-33fd-4d57-a086-9688ecdac764
[2023-06-24T10:38:17.446+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 423, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.19.0.8:7077 --name arrow-spark /opt/***/dags/spark_etl_simple.py. Error code is: 1.
[2023-06-24T10:38:17.449+0000] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=spark_***_dag_v2, task_id=spark_submit_task, execution_date=20230624T103712, start_date=20230624T103713, end_date=20230624T103817
[2023-06-24T10:38:17.461+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 60 for task spark_submit_task (Cannot execute: spark-submit --master spark://172.19.0.8:7077 --name arrow-spark /opt/***/dags/spark_etl_simple.py. Error code is: 1.; 644)
[2023-06-24T10:38:17.482+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-24T10:38:17.493+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
